#! /bin/bash -x
set -e
# -target 1.1
cd src
# javac -target 1.1 -deprecation View5D_.java
javac -deprecation -classpath "." View5D_.java
jar -cf View5D_.jar *.class 
# cp /*.class /usr/local/ImageJ/plugins/View5D/
cp View5D_.jar /usr/local/ImageJ/plugins/View5D/
# cp View5D_.jar /windows/C/DriveF/JavaProgs/ImageJ/plugins/View5D/
cp View5D_.jar /windows/D/JavaProgs/ImageJ/plugins/View5D/
mv View5D_.jar ..
cd ..
zip -r View5DImageJ.zip View5D_.jar *.html *.jpg *.m *.policy examples COPYING
zip -r View5DSources.zip src/View5D_.java COPYING javacApplet javacImageJ Makefile *.m

cp View5D.html /usr/local/ImageJ/plugins/View5D/index.html
cp *.html /usr/local/ImageJ/plugins/View5D/
cp -r examples/* /usr/local/ImageJ/plugins/View5D/examples/
# cp *.class /net/mobi1/data1/WinApps/ImageJ/plugins/View5D/
# cp View5D.html /net/mobi1/data1/WinApps/ImageJ/plugins/View5D/index.html
# cp -r examples /net/mobi1/data1/WinApps/ImageJ/plugins/View5D/
# cp *.class /net/mobi1/data1/MacOSX_local/ImageJ/plugins/View5D/
