#! /bin/bash -x
set -e
# -target 1.1
cd src
# javac -target 1.1 -deprecation View5D_.java
rm *.class
javac -target 1.1 -source 1.2 -deprecation -classpath "." View5D_.java
jar -cf View5D_.jar *.class 
# cp /*.class /usr/local/ImageJ/plugins/View5D/
cp View5D_.jar /usr/local/ImageJ/plugins/View5D/
# cp View5D_.jar /windows/C/DriveF/JavaProgs/ImageJ/plugins/View5D/
cp View5D_.jar /windows/D/JavaProgs/ImageJ/plugins/View5D/View5D.jar
cp View5D_.jar /usr/local/KhorosInstall/goodies/data/display/View5D.jar
cp View5D_.jar /usr/local/matlab/java/jar/toolbox/View5D.jar
cp View5D_.jar /usr/local/dip/common/dipimage/private/View5D.jar
cp View5D_.jar ../examples/View5D.jar
mv View5D_.jar ..
cd ..
zip -r View5D.zip View5D_.jar *.html *.jpg *.m *.policy examples COPYING
zip -r View5DSources.zip src/*.java COPYING javacImageJ Makefile *.m

cp View5D.html /usr/local/ImageJ/plugins/View5D/index.html
cp *.html /usr/local/ImageJ/plugins/View5D/
cp -r examples/* /usr/local/ImageJ/plugins/View5D/examples/
# cp *.class /net/mobi1/data1/WinApps/ImageJ/plugins/View5D/
# cp View5D.html /net/mobi1/data1/WinApps/ImageJ/plugins/View5D/index.html
# cp -r examples /net/mobi1/data1/WinApps/ImageJ/plugins/View5D/
# cp *.class /net/mobi1/data1/MacOSX_local/ImageJ/plugins/View5D/
