#! /bin/bash -x
set -e
cat src/View5D_.java | sed "s/public class View5D_/class View5D_/" | sed "s/class View5D /public class View5D /" | sed "s/ GenericDialog/ AGenericDialog/g" > /tmp/View5D.java
# | sed "s/import ij.*$//g"
javac -target 1.1 -deprecation /tmp/View5D.java -classpath "." # -Xlint:unchecked 
mv /tmp/*.class .
jar -cf View5D.jar *.class ij 
cp View5D.jar /usr/local/KhorosInstall/goodies/data/display/
cp View5D.jar /tmp/
cp View5D.jar /usr/local/matlab/java/jar/toolbox/View5D.jar
cp View5D.jar /usr/local/dip/toolbox/dipimage/private/View5D.jar
# cp View5D.jar /windows/C/Program\ Files/matlab/R2006a/java/jar/toolbox/
# cp View5D.jar /windows/C/Program\ Files/matlab/R2006b/java/jar/toolbox/
zip -r View5DApplet.zip *.class *.jar *.html *.jpg *.m *.policy examples/ COPYING
# ij/
rm /tmp/View5D.java
mv *.class *.jar examples/
# cp View5D.html /net/mobi1/data2/WinApps/ImageJ/plugins/View5D/index.html
# cp -r examples/ /net/mobi1/data2/WinApps/ImageJ/plugins/View5D/
