/* Generated By:JJTree: Do not edit this line. /Users/singularsys/Documents/workspace/jep-newcvs/src/org/nfunk/jep/ParserVisitor.java */

package org.nfunk.jep;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws ParseException;
  public Object visit(ASTStart node, Object data) throws ParseException;
  public Object visit(ASTFunNode node, Object data) throws ParseException;
  public Object visit(ASTVarNode node, Object data) throws ParseException;
  public Object visit(ASTConstant node, Object data) throws ParseException;
}
