#!/bin/bash

DEBIAN_DIRECTORY=$(dirname $(readlink -f "$BASH_SOURCE"))
export JAVA_HOME=`cat "$DEBIAN_DIRECTORY"/java-home`
JAVAC_PATH=$JAVA_HOME/bin/javac

if [ ! -e "$JAVAC_PATH" ]
then
    echo Could not find the Java compiler at "$JAVAC_PATH"
    exit 1
fi

echo In build-command, found JAVA_HOME was $JAVA_HOME

sh -x Fake.sh FALLBACK=false VERBOSE=true "CLASSPATH(plugins/VIB_.jar)=/usr/share/java/vecmath.jar:/usr/share/java/j3dutils.jar:/usr/lib/jni/libj3dcore-ogl.so:/usr/share/java/j3dcore.jar:/usr/share/java/jama.jar:/usr/share/java/junit4.jar:/usr/share/java/jzlib.jar:jars/VIB-lib.jar:jars/pal-optimization.jar:plugins/3D_Viewer.jar" \
    "CLASSPATH(plugins/mpicbg_.jar)=:/usr/share/java/jama.jar" \
    "CLASSPATH(plugins/TrakEM2_.jar)=plugins/VIB_.jar:plugins/loci_tools.jar:plugins/mpicbg_.jar:plugins/level_sets.jar:plugins/bUnwarpJ_.jar:plugins/Fiji_Plugins.jar:/usr/share/java/vecmath.jar:/usr/share/java/j3dutils.jar:/usr/lib/jni/libj3dcore-ogl.so:/usr/share/java/j3dcore.jar:/usr/share/java/jama.jar:/usr/share/java/jfreechart.jar:/usr/share/java/postgresql.jar:plugins/Simple_Neurite_Tracer.jar:plugins/3D_Viewer.jar" \
    "CLASSPATH(jars/fiji-scripting.jar)=/usr/share/java/jython.jar:/usr/share/java/bsh.jar:/usr/share/java/js.jar" \
    "CLASSPATH(plugins/BeanShell_Interpreter.jar)=/usr/share/java/bsh.jar" \
    "CLASSPATH(plugins/IO_.jar)=/usr/share/java/batik-all.jar:/usr/share/java/xml-apis-ext.jar" \
    "CLASSPATH(jars/zs.jar)=/usr/share/java/jama.jar" \
    "CLASSPATH(plugins/Jython_Interpreter.jar)=/usr/share/java/jython.jar:jars/fiji-scripting.jar" \
    "CLASSPATH(plugins/Clojure_Interpreter.jar)=/usr/share/java/clojure.jar" \
    "CLASSPATH(plugins/IO_.jar)=/usr/share/java/itext1.jar:/usr/share/java/batik-all.jar:/usr/share/java/xml-apis-ext.jar:/usr/share/java/jzlib.jar" \
    "CLASSPATH(plugins/Directionality_.jar)=/usr/share/java/jfreechart.jar:/usr/share/java/jcommon.jar" \
    "CLASSPATH(plugins/Fiji_Plugins.jar)=/usr/share/java/jsch.jar:jars/fiji-lib.jar" \
    "CLASSPATH(misc/Fiji.jar)=/usr/share/java/jsch.jar" \
    "CLASSPATH(plugins/Image_Expression_Parser.jar)=jars/jep.jar:jars/imglib.jar:/usr/share/java/junit4.jar" \
    "CLASSPATH(jars/jep.jar)=/usr/share/java/jama.jar:/usr/share/java/junit4.jar" \
    "CLASSPATH(plugins/Javascript_.jar)=/usr/share/java/js.jar" \
    "CLASSPATH(plugins/Fiji_Updater.jar)=/usr/share/java/jsch.jar" \
    "CLASSPATH(jars/pal-optimization.jar)=/usr/share/java/junit4.jar" \
    "CLASSPATH(plugins/Simple_Neurite_Tracer.jar)=jars/VIB-lib.jar:plugins/VIB_.jar:jars/pal-optimization.jar:/usr/share/java/junit4.jar:plugins/3D_Viewer.jar:/usr/share/java/j3dcore.jar:/usr/share/java/vecmath.jar:/usr/share/java/batik-all.jar:jars/commons-math.jar:/usr/share/java/j3dutils.jar:/usr/share/java/jfreechart.jar:/usr/share/java/jcommon.jar" \
    "CLASSPATH(plugins/3D_Viewer.jar)=jars/VIB-lib.jar:jars/imglib.jar:jars/Jama-1.0.2.jar:/usr/share/java/j3dcore.jar:/usr/share/java/vecmath.jar:/usr/share/java/j3dutils.jar" \
    "CLASSPATH(jars/VIB-lib.jar)=jars/Jama-1.0.2.jar:/usr/share/java/junit4.jar:jars/pal-optimization.jar:/usr/share/java/jzlib.jar" \
    "CLASSPATH(jars/VectorString.jar)=jars/Jama-1.0.2.jar:/usr/share/java/vecmath.jar:/usr/share/java/j3dcore.jar" \
    "CLASSPATH(jars/imglib.jar)=/usr/share/java/j3dcore.jar:/usr/share/java/vecmath.jar" \
    "CLASSPATH(plugins/Fiji_Developer.jar)=/usr/share/java/j3dcore.jar:plugins/Script_Editor.jar:plugins/Fiji_Plugins.jar:jars/rsyntaxtextarea.jar:plugins/3D_Viewer.jar:/usr/share/java/j3dutils.jar:/usr/share/java/vecmath.jar" \
    "CLASSPATH(plugins/SPIM_Registration.jar)=/usr/share/java/vecmath.jar:jars/imglib.jar:jars/mpicbg.jar:plugins/3D_Viewer.jar:jars/weka.jar:jars/fiji-lib.jar:plugins/loci_tools.jar:plugins/Fiji_Plugins.jar:jars/VIB-lib.jar:/usr/share/java/jama.jar:/usr/share/java/j3dcore.jar:/usr/share/java/j3dutils.jar" \
    "$@"
