#!/bin/sh

set -e

echo === Checking this is a clean working tree:
debian/update-debian.py --check-git-clean

echo === Generating a new build-command from the Fakefile
debian/update-debian.py --generate-build-command

echo === Generating a new build-command from the Fakefile
debian/rewrite-pom-files.py

echo === Cleaning the tree:
debian/update-debian.py --clean

echo ==== Building the tree:
debian/build-command

echo ==== Generating a new debian/control:
debian/update-debian.py --generate-complete-control

echo ==== Cleaning again:
debian/update-debian.py --clean

echo ==== Finally, building the packages:
dpkg-buildpackage -I.git -Iwekadocs -Ibio-formats/dist -rfakeroot -us -uc
