Document: fiji
Title: Debian fiji Manual
Author: <insert document author here>
Abstract: This manual describes what fiji is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fiji/fiji.sgml.gz

Format: postscript
Files: /usr/share/doc/fiji/fiji.ps.gz

Format: text
Files: /usr/share/doc/fiji/fiji.text.gz

Format: HTML
Index: /usr/share/doc/fiji/html/index.html
Files: /usr/share/doc/fiji/html/*.html

  
